# An optional prepared SDK keeps patched Qmmp and TagLib out of system paths.
# The application can also be configured with the individual LISTENFREE_* paths.
set(KOS_LISTENFREE_SDK "$ENV{KOS_LISTENFREE_SDK}" CACHE PATH "ListenFree SDK containing prefix, deps/usr and vendor")
if(KOS_LISTENFREE_SDK)
    foreach(_component WebEngineWidgets WebEngineCore WebEngineCoreTools WebChannel Positioning)
        set(_config "${KOS_LISTENFREE_SDK}/deps/usr/lib/${CMAKE_LIBRARY_ARCHITECTURE}/cmake/Qt6${_component}")
        if(EXISTS "${_config}/Qt6${_component}Config.cmake" AND NOT Qt6${_component}_DIR)
            set(Qt6${_component}_DIR "${_config}" CACHE PATH "SDK Qt component" FORCE)
        endif()
    endforeach()
    list(PREPEND CMAKE_PREFIX_PATH "${KOS_LISTENFREE_SDK}/prefix" "${KOS_LISTENFREE_SDK}/deps/usr")
    set(LISTENFREE_QMMP_SOURCE_ROOT "${KOS_LISTENFREE_SDK}/vendor/qmmp-2.4.1" CACHE PATH "Patched Qmmp source")
    set(LISTENFREE_QMMP_LIBRARY "${KOS_LISTENFREE_SDK}/prefix/lib/libqmmp.so" CACHE FILEPATH "Qmmp library")
    set(LISTENFREE_QMMP_RUNTIME "${KOS_LISTENFREE_SDK}/prefix/lib/libqmmp.so" CACHE FILEPATH "Qmmp runtime")
    set(LISTENFREE_QMMP_UI_LIBRARY "${KOS_LISTENFREE_SDK}/prefix/lib/libqmmpui.so" CACHE FILEPATH "Qmmp UI library")
    set(LISTENFREE_QMMP_PLUGIN_ROOT "${KOS_LISTENFREE_SDK}/prefix/lib/qmmp-2.4" CACHE PATH "Patched Qmmp plugins")
    set(LISTENFREE_LIVE_FFMPEG_ROOT "${KOS_LISTENFREE_SDK}/deps/usr" CACHE PATH "FFmpeg prefix")
    set(OPENSSL_ROOT_DIR "${KOS_LISTENFREE_SDK}/deps/usr" CACHE PATH "OpenSSL prefix")
endif()
