// Generated by the desktop shell. Do not edit: it is
// overwritten from WeatherService on a timer.
import QtQuick
QtObject {
    property string weatherSymbol: "☁"
    property string weatherTemperature: "25°"
    property string weatherCity: "长沙"
    property string weatherCondition: "大部晴朗"
    property string weatherApparent: "27°"
    property string weatherHumidity: "71%"
    property double generatedAt: 1789644500000
}
