pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import QtCore
import qs.desktop.modules.platform

// Feeds the lock screen its weather.
//
// The lock screen is kscreenlocker's greeter, not this shell: it is a
// different process, with none of Quickshell's types, no D-Bus bindings and
// -- measured, not assumed -- no way to read a file at all. XMLHttpRequest is
// gated behind QML_XHR_ALLOW_FILE_READ, an environment variable the greeter's
// launcher does not set, and Qt.include did not load a local script under any
// form tried. What QML loading *does* do is load QML: so the feed is written
// as a small QML file into the installed theme package, where the lock screen
// picks it up with a plain Loader.
//
// The file is data only -- five property assignments, no logic -- and it is
// written atomically (tmp, then mv) so a lock screen never sees a half file.
// The `test -f` guard keeps a desktop that is not running this theme from
// creating an empty package directory as a side effect.
QtObject {
    id: service

    // Where kscreenloader looks: the generic data location is what
    // `plasma-lookup` and the greeter both resolve for look-and-feel and shell
    // packages, and it is user-writable by construction.
    readonly property string packageDir:
        StandardPaths.writableLocation(StandardPaths.GenericDataLocation)
        + "/plasma/shells/org.kos.desktop/contents/lockscreen"

    readonly property int refreshMinutes: 5

    function initialize() {
        write()
    }

    function qmlString(value) {
        // JSON strings are valid QML strings, and this escapes everything that
        // needs escaping -- a city name with a quote in it must not end up as
        // QML syntax.
        return JSON.stringify(String(value ?? ""))
    }

    // The lock screen shows what the Dock's weather page shows -- the numbers
    // a glance is actually for -- and no more: a lock screen is not where a
    // forecast gets read.
    function payload() {
        if (!WeatherService.available)
            return ""
        const symbol = WeatherService.conditionSymbol(
            WeatherService.weatherCode, WeatherService.isDay)
        return "// Generated by the desktop shell. Do not edit: it is\n"
            + "// overwritten from WeatherService on a timer.\n"
            + "import QtQuick\n"
            + "QtObject {\n"
            + "    property string weatherSymbol: " + qmlString(symbol) + "\n"
            + "    property string weatherTemperature: "
                + qmlString(WeatherService.temperature) + "\n"
            + "    property string weatherCity: " + qmlString(WeatherService.cityName) + "\n"
            + "    property string weatherCondition: "
                + qmlString(WeatherService.conditionText(WeatherService.weatherCode)) + "\n"
            + "    property string weatherApparent: "
                + qmlString(WeatherService.apparentTemperature) + "\n"
            + "    property string weatherHumidity: " + qmlString(WeatherService.humidity) + "\n"
            + "    property double generatedAt: " + Date.now() + "\n"
            + "}\n"
    }

    function write() {
        const body = payload()
        if (body === "")
            return
        const proc = _procFactory.createObject(service, { command: [
            "sh", "-c",
            // The theme has to already be installed here for this to be worth
            // anything, so let that test gate the whole write.
            "test -f \"$1/LockScreen.qml\""
            + " && printf %s \"$2\" > \"$1/LockFeed.qml.tmp\""
            + " && mv \"$1/LockFeed.qml.tmp\" \"$1/LockFeed.qml\"",
            "lock-feed-save",
            service.packageDir,
            body
        ] })
        if (proc) {
            proc.exited.connect(function (code) {
                const stderr = proc.stderr?.text ?? ""
                if (code !== 0)
                    console.warn("[LockScreenFeed] write skipped or failed code="
                        + code + " stderr=" + stderr)
                proc.destroy()
            })
            proc.running = true
        }
    }

    // WeatherService refreshes about once an hour and pushes on change; the
    // timer is what keeps a stalled push from going stale on the lock screen.
    property Timer _timer: Timer {
        interval: service.refreshMinutes * 60 * 1000
        running: true
        repeat: true
        triggeredOnStart: true
        onTriggered: service.write()
    }

    property Connections _weather: Connections {
        target: WeatherService
        function onCurrentChanged() {
            service.write()
        }
    }

    property Component _procFactory: Component {
        Process {
            stdout: StdioCollector {}
            stderr: StdioCollector {}
        }
    }
}
