import assert from 'node:assert/strict';
import {covered, cadence} from './ThemeWallpaperPolicy.mjs';
const screen = {name:'DP-1', x:0, y:0, width:1920, height:1080};
const app = {screenName:'DP-1', isFullscreen:true, isVisible:true, desktopIds:['one']};
assert.equal(covered(screen, [app], 'one'), true);
assert.equal(covered(screen, [{screenName:'DP-1', toplevel:{fullscreen:true,minimized:false}}], 'one'), true);
assert.equal(covered(screen, [{screenName:'DP-1', toplevel:{fullscreen:true,minimized:true}}], 'one'), false);
assert.equal(covered(screen, [{...app,isMinimized:true}], 'one'), false);
assert.equal(covered(screen, [app], 'two'), false);
assert.equal(covered(screen, [{...app,screenName:'DP-2'}], 'one'), false);
assert.equal(covered(screen, [{isMaximized:true,geometry:{x:0,y:32,width:1920,height:1000}}], 'one'), true);
assert.equal(covered(screen, [{geometry:{x:100,y:100,width:800,height:600}}], 'one'), false);
assert.equal(cadence(false,false,false,false,true),67);
assert.equal(cadence(true,false,false,false,true),125);
assert.equal(cadence(false,true,false,false,true),125);
assert.equal(cadence(false,false,true,false,true),0);
assert.equal(cadence(false,false,false,true,true),0);
assert.equal(cadence(false,false,false,false,false),0);
console.log('Theme wallpaper: coverage, desktops, power cadence, reduced motion and lock pause passed.');
