// Cached background reconstruction and foreground matte are generated by the
// isolated AI worker. A soft near-field map gives protruding objects slightly
// more travel without slicing the subject into disconnected pieces.
#version 440

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;
layout(binding = 1) uniform sampler2D source;
layout(binding = 2) uniform sampler2D background;
layout(binding = 3) uniform sampler2D matte;
layout(binding = 4) uniform sampler2D influence;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;
    vec2 pointer;
    vec2 cropScale;
} ubuf;

void main()
{
    const float margin = 0.05;
    vec2 croppedUv = vec2(0.5) + (qt_TexCoord0 - vec2(0.5))
        * ubuf.cropScale * (1.0 - 2.0 * margin);
    float nearWeight = texture(influence, croppedUv).r;
    vec2 backgroundUv = clamp(croppedUv - ubuf.pointer
        * (0.005 * ubuf.cropScale), vec2(0.001), vec2(0.999));
    vec2 foregroundUv = clamp(croppedUv + ubuf.pointer
        * ((0.020 + 0.010 * nearWeight) * ubuf.cropScale),
        vec2(0.001), vec2(0.999));
    float opacity = texture(matte, foregroundUv).r;
    vec3 backgroundColor = texture(background, backgroundUv).rgb;
    vec3 foregroundColor = texture(source, foregroundUv).rgb;
    fragColor = vec4(mix(backgroundColor, foregroundColor, opacity), 1.0)
        * ubuf.qt_Opacity;
}
